# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('store', models.CharField(choices=[('AH', 'Albert Heijn'), ('SL', 'Sligro')], default='SL', max_length=2)),
                ('description_of_amount', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('method', models.TextField()),
                ('time', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Recipelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRecipelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
                ('recipelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipelist')),
            ],
        ),
        migrations.CreateModel(
            name='Shoppinglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shoppinglist', max_length=128)),
                ('dateadded', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppinglistIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('shoppinglist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='ingredient',
            field=models.ManyToManyField(through='recipes.ShoppinglistIngredient', to='recipes.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipelist',
            name='recipe',
            field=models.ManyToManyField(through='recipes.RecipeRecipelist', to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='recipes.RecipeIngredient', to='recipes.Ingredient'),
        ),
    ]
