# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20160904_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description_of_amount',
            field=models.CharField(default='Per stuk', max_length=128),
        ),
    ]
