# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20160906_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True),
        ),
    ]
