# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20160907_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=15, validators=[recipes.models.validate_mod_five]),
        ),
    ]
