# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.IngredientCategory'),
            preserve_default=False,
        ),
    ]
