# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20160907_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dateadded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
