# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20160907_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='came_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.RecipeCame_From', verbose_name='Came from'),
        ),
    ]
