# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20160907_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': '1. Ingredienten'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recept', 'verbose_name_plural': '2. Recepten'},
        ),
        migrations.AlterModelOptions(
            name='recipelist',
            options={'verbose_name': 'Receptenlijst', 'verbose_name_plural': '3. Receptenlijsten'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Boodschappenlijst', 'verbose_name_plural': '4. Boodschappenlijsten'},
        ),
        migrations.AlterField(
            model_name='recipecame_from',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Category'),
        ),
    ]
