# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20160908_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
