# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-08 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20160908_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipelist',
            name='dateadded',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
